"use strict";
exports.__esModule = true;
var Phoenix_1 = require("./lib/Phoenix/Phoenix");
var Player_1 = require("./lib/Player/Player");
var Enemy_1 = require("./lib/Enemy/Enemy");
var dk = new Player_1["default"]("dark_knight", 100, true);
var leviathon = new Player_1["default"]("leviathon", 50, false);
var phoenix = new Phoenix_1["default"](dk.username, 101, dk.radiant);
dk.getInfo();
console.log("-");
leviathon.getInfo();
console.log("-");
dk.addKill();
console.log("-");
dk.getInfo();
console.log("-");
phoenix.listPowers();
console.log("-");
phoenix.addKill();
phoenix.addKill();
console.log("-");
phoenix.getInfo();
console.log("------------------------");
console.log("------------------------");
console.log("------------------------");
console.log("------------------------");
var bob = new Enemy_1["default"]("Robert", 3394485577);
bob.printName();
console.log("---");
bob.changeNameAndSsn("Jane", 1102293384);
console.log("---");
bob.printName();
